### ISSUE TITLE
Q to R upgrade failed at repo build

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-upgrades#380]
TASK [repo_build : Create OpenStack-Ansible requirement wheels] ****************************************************************************************************************************************```
fatal: [infra01_repo_container-d9b150e3]: FAILED! => {"changed": true, "cmd": "set -o pipefail; /openstack/venvs/repo-build-r18.0.1/bin/pip wheel --timeout 120 --wheel-dir /tmp/openstack-wheel-output --find-links /var/www/repo/links --find-links /tmp/openstack-wheel-output --constraint /var/www/repo/os-releases/r18.0.1/ubuntu-16.04-x86_64/requirements_constraints.txt  --no-binary libvirt-python  --index-url https://pypi.python.org/simple --trusted-host pypi.python.org  --build /tmp/openstack-builder --requirement /var/www/repo/os-releases/r18.0.1/ubuntu-16.04-x86_64/requirements.txt  2>
&1 | ts > /var/log/repo/wheel_build.log```

Error:
```
Oct 19 09:21:57   Cloning file:///var/www/repo/openstackgit/networking-calico (to revision 79bdf4995d102833d23479180350216fc59e4b94) to /tmp/openstack-builder/networking-calico
Oct 19 09:21:57 Note: checking out '79bdf4995d102833d23479180350216fc59e4b94'.
Oct 19 09:21:57
Oct 19 09:21:57 You are in 'detached HEAD' state. You can look around, make experimental
Oct 19 09:21:57 changes and commit them, and you can discard any commits you make in this
Oct 19 09:21:57 state without impacting any branches by performing another checkout.
Oct 19 09:21:57
Oct 19 09:21:57 If you want to create a new branch to retain commits you create, you may
Oct 19 09:21:57 do so (now or later) by using -b with the checkout command again. Example:
Oct 19 09:21:57
Oct 19 09:21:57   git checkout -b <new-branch-name>
Oct 19 09:21:57
Oct 19 09:21:57     Complete output from command python setup.py egg_info:
Oct 19 09:21:57     ERROR:root:Error parsing
Oct 19 09:21:57     Traceback (most recent call last):
Oct 19 09:21:57       File "/openstack/venvs/repo-build-r18.0.1/local/lib/python2.7/site-packages/pbr/core.py", line 96, in pbr
Oct 19 09:21:57         attrs = util.cfg_to_args(path, dist.script_args)
Oct 19 09:21:57       File "/openstack/venvs/repo-build-r18.0.1/local/lib/python2.7/site-packages/pbr/util.py", line 259, in cfg_to_args
Oct 19 09:21:57         pbr.hooks.setup_hook(config)
Oct 19 09:21:57       File "/openstack/venvs/repo-build-r18.0.1/local/lib/python2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
Oct 19 09:21:57         metadata_config.run()
Oct 19 09:21:57       File "/openstack/venvs/repo-build-r18.0.1/local/lib/python2.7/site-packages/pbr/hooks/base.py", line 27, in run
Oct 19 09:21:57         self.hook()
Oct 19 09:21:57       File "/openstack/venvs/repo-build-r18.0.1/local/lib/python2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
Oct 19 09:21:57         self.config['name'], self.config.get('version', None))
Oct 19 09:21:57       File "/openstack/venvs/repo-build-r18.0.1/local/lib/python2.7/site-packages/pbr/packaging.py", line 824, in get_version
Oct 19 09:21:57         version = _get_version_from_git(pre_version)
Oct 19 09:21:57       File "/openstack/venvs/repo-build-r18.0.1/local/lib/python2.7/site-packages/pbr/packaging.py", line 764, in _get_version_from_git
Oct 19 09:21:57         result = _get_version_from_git_target(git_dir, target_version)
Oct 19 09:21:57       File "/openstack/venvs/repo-build-r18.0.1/local/lib/python2.7/site-packages/pbr/packaging.py", line 726, in _get_version_from_git_target
Oct 19 09:21:57         dict(new=new_version, target=target_version))
Oct 19 09:21:57     ValueError: git history requires a target version of pbr.version.SemanticVersion(3.9.2), but target version is pbr.version.SemanticVersion(3.8.4)
Oct 19 09:21:57     error in setup command: Error parsing /tmp/openstack-builder/networking-calico/setup.cfg: ValueError: git history requires a target version of pbr.version.SemanticVersion(3.9.2), but target version is pbr.version.SemanticVersion(3.8.4)

```
We downgraded networking-calico to the previous sha 87e780110d3ba0f0b57154ad74f9254aa950acda and
upgrades pbr to 4.2.0 inside the repo venv

**Comment by antonym** [comment]
Tracking https://bugs.launchpad.net/networking-calico/+bug/1849110 for this.

**Comment by BjoernT** [comment]
Opened a OSA bug https://bugs.launchpad.net/openstack-ansible/+bug/1849494

**Comment by BjoernT** [comment]
Just build a Rocky AIO and the problem doesnt exist anymore as the SHAs have updated.
Once the planned upgrade finishes I close the issue
